name: Check

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  gradle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build and test with Gradle
        run: ./gradlew clean check
        # https://github.com/marketplace/actions/junit-report-action
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'build/test-results/*/*.xml'
          check_name: 'JUnit test report (gradle)'
          require_passed_tests: true


  maven:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.7.0
        with:
          java-version: 17
          java-distribution: temurin
          maven-version: 3.9.0
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Generate sources with Gradle
        run: ./gradlew regenerateSources
      - name: Build and test with Maven
        run: mvn clean verify # -Dmaven.test.failure.ignore=true
        # https://github.com/marketplace/actions/junit-report-action
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'target/surefire-reports/*.xml'
          check_name: 'JUnit test report (maven)'
          require_passed_tests: true
